-- ============================================================
-- Tabel Kata Baku dan Tidak Baku
-- Sumber: brainacademy.id
-- ============================================================

CREATE TABLE IF NOT EXISTS kata_baku (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    kata_baku   VARCHAR(100) NOT NULL,
    kata_tidak_baku VARCHAR(200) NOT NULL
);

INSERT INTO kata_baku (kata_baku, kata_tidak_baku) VALUES
-- Huruf A
('Aberasi', 'abrasi'),
('Absorpsi', 'absorsi'),
('Adab', 'adap'),
('Adhesi', 'adesi'),
('Adibusana', 'adi busana'),
('Adidaya', 'adi daya'),
('Adjektif', 'ajektif'),
('Administrator', 'admin'),
('Advokat', 'adpokat'),
('Afdal', 'afdol'),
('Agamais', 'agamis'),
('Ajek', 'ajeg'),
('Akhirat', 'akherat'),
('Aksesori', 'asesoris'),
('Aktif', 'aktip'),
('Aktivitas', 'aktifitas'),
('Aktual', 'aktuil'),
('Akuarium', 'aquarium'),
('Aluminium', 'almunium'),
('Ambulans', 'ambulan'),
('Analisis', 'analisa'),
('Andal', 'handal'),
('Antena', 'antene'),
('Antre', 'antri'),
('Anugerah', 'anugrah'),
('Aparat', 'aparatur'),
('Apostrof', 'opostrop'),
('Apotek', 'apotik'),
('Asas', 'azas'),
('Asasi', 'azasi'),
('Atlet', 'atlit'),
('Atmosfer', 'atmosfir'),
('Auditorium', 'aditorium'),
('Autentik', 'otentik'),
('Autopsi', 'otopsi'),
('Azan', 'adzan'),

-- Huruf B
('Baka', 'baqa'),
('Balig', 'baligh'),
('Balsam', 'balsem'),
('Banderol', 'bandrol'),
('Barzakh', 'barzah'),
('Batalion', 'batalyon'),
('Baterai', 'batere'),
('Batil', 'bathil'),
('Bayangkara', 'bhayangkara'),
('Bazar', 'bazaar'),
('Becermin', 'bercermin'),
('Bengkuang', 'bengkoang'),
('Benzol', 'bensol'),
('Besok', 'esok'),
('Beterbangan', 'berterbangan'),
('Biseps', 'bisep'),
('Blanko', 'blangko'),
('Blender', 'belender'),
('Boks', 'bok'),
('Bolpoin', 'bolpen'),
('Bosan', 'bosen'),
('Bumper', 'bemper'),
('Bungker', 'bangker'),
('Bus', 'bis'),

-- Huruf C
('Cabai', 'cabe'),
('Capai', 'cape, capek'),
('Capcai', 'cap cai'),
('Cedera', 'cidera'),
('Cendekia', 'cendikia'),
('Cendekiawan', 'cendikiawan'),
('Cengkeram', 'cengkram'),
('Cengkerama', 'cengkrama'),
('Cengkih', 'cengkeh'),
('Cinderamata', 'cenderamata'),
('Cokelat', 'coklat'),

-- Huruf D
('Daftar', 'daptar'),
('Dai', 'da''i'),
('Dakwah', 'da''wah'),
('Darma', 'dharma'),
('Debit', 'debet'),
('Debitor', 'debitur'),
('Dekret', 'dekrit'),
('Deodoran', 'deodorant'),
('Depot', 'depo'),
('Deputi', 'deputy'),
('Derajat', 'derajad'),
('Desain', 'design'),
('Detail', 'detil'),
('Detergen', 'deterjen'),
('Deviasi', 'defiasi'),
('Diagnosis', 'diagnosa'),
('Dispenser', 'despenser'),
('Distilasi', 'destilasi'),
('Dividen', 'deviden'),
('Donatur', 'donator'),
('Durian', 'duren'),

-- Huruf E
('Efektif', 'efektip'),
('Efektivitas', 'efektifitas'),
('Ekosistem', 'ekosistim'),
('Eksem', 'eksim'),
('Ekshibisi', 'eksibisi'),
('Ekspor', 'eksport'),
('Ekstra', 'extra'),
('Ekstrakurikuler', 'ekstrakulikuler'),
('Ekstrem', 'ekstrim'),
('Ekuivalen', 'ekwivalen, equivalen'),
('Elektrode', 'elektroda'),
('Elips', 'elip'),
('Elite', 'elit'),
('Emas', 'mas'),
('Embus', 'hembus'),
('Empas', 'hempas'),
('Enjin', 'engine'),
('Ensiklopedia', 'ensiklopedi'),
('Episode', 'episod'),
('Epos', 'ephos'),
('Esai', 'essai'),
('Esens', 'esen'),
('Eskadron', 'sekuadron'),
('Etanol', 'ethanol'),

-- Huruf F
('Fakih', 'faqih'),
('Faksimili', 'faksimil'),
('Familier', 'familiar'),
('Farmakope', 'farmakop'),
('Favorit', 'pavorit'),
('Februari', 'pebruari'),
('Feri', 'peri'),
('Filipina', 'philipina'),
('Film', 'filem'),
('Filsuf', 'filosof'),
('Finis', 'finish'),
('Flat', 'plat'),
('Folio', 'polio'),
('Formal', 'formil'),
('Foto', 'photo'),
('Fotokopi', 'foto copy'),
('Fotosintensis', 'fotosintesa'),
('Frekuensi', 'frekwensi'),

-- Huruf G
('Gaib', 'ghaib'),
('Galaktosa', 'galaktose'),
('Galeri', 'galery'),
('Gap', 'gep'),
('Geiser', 'geyser'),
('Geladi bersih', 'geladi resik'),
('Gelondong', 'glondong'),
('Genealogi', 'geneologi'),
('Genius', 'jenius'),
('Genting', 'genteng'),
('Gerebek', 'grebek'),
('Gereget', 'greget'),
('Gerendel', 'grendel'),
('Gips', 'gip'),
('Glamor', 'glamour'),
('Glaukoma', 'glukoma'),
('Glosarium', 'glosary'),
('Glukosa', 'glukose'),
('Gongseng', 'ongseng'),
('Griya', 'gria'),
('Grup', 'group'),
('Gua', 'goa'),
('Gubuk', 'gubug'),
('Gudeg', 'gudek'),
('Guncang', 'goncang'),

-- Huruf H
('Hadis', 'hadist'),
('Hafal', 'hapal'),
('Hakikat', 'hakekat'),
('Hal-hal', 'hal-ihwal'),
('Hektare', 'hektar'),
('Heterogen', 'hetrogen'),
('Hidraulis', 'hidrolis'),
('Hierarki', 'hirarki'),
('Hieroglif', 'hiroglif'),
('Higienis', 'higenis'),
('Himne', 'hymne'),
('Hipermetropia', 'hipermetri'),
('Hipotek', 'hipotik'),
('Hipotesis', 'hipotesa'),
('Hipovitaminosis', 'hipovitaminose'),

-- Huruf I
('Ibtidaiah', 'ibtidaiyah'),
('Idah', 'iddah'),
('Ideal', 'idial'),
('Ideologi', 'idiologi'),
('Ihwal', 'ikhwal'),
('Ijazah', 'ijasah'),
('Ikat', 'iket'),
('Ikhlas', 'ihlas'),
('Iktibar', 'i''tibar'),
('Iktikaf', 'i''tikaf'),
('Ilusi', 'illusi'),
('Imbau', 'himbau'),
('Impit', 'himpit'),
('Impor', 'import'),
('Indra', 'indera'),
('Influenza', 'influensa'),
('Inframerah', 'infra merah'),
('Infus', 'inpus'),
('Ingar-bingar', 'hingar-bingar'),
('Inkam', 'income'),
('Inkognito', 'incognito'),
('Insting', 'instink'),
('Intelijen', 'inteligen'),
('Intens', 'inten'),
('Interogasi', 'interograsi'),
('Introspeksi', 'interopeksi'),
('Isap', 'hisap'),
('Izin', 'ijin'),

-- Huruf J
('Jadwal', 'jadual'),
('Jagat', 'jagad'),
('Jahiliah', 'jahiliyah'),
('Jajar', 'jejer'),
('Jamaah', 'jemaah'),
('Jenderal', 'jendral'),
('Jenius', 'genius'),
('Jerapah', 'zarafah'),
('Jeriken', 'jerigen'),
('Jip', 'jeep'),
('Joging', 'jogging'),
('Join', 'joint'),
('Jorjoran', 'jor-joran'),
('Jubileum', 'jubilum'),
('Judo', 'yudo'),
('Jujitsu', 'jiujitsu'),
('Junior', 'yunior'),
('Junktur', 'jungtur'),
('Juz', 'jus'),

-- Huruf K
('Kacamata', 'kaca mata'),
('Kafah', 'kaffah'),
('Kafetaria', 'cafetaria'),
('Kaidah', 'kaedah'),
('Kakbah', 'ka''bah'),
('Kaleidoskop', 'kaleidioskop'),
('Kalkarium', 'kalkarim'),
('Kamerawan', 'kameramen'),
('Kamuflase', 'kamuplase'),
('Kanguru', 'kangguru'),
('Kanker', 'kangker'),
('Kantong', 'kantung'),
('Karburasi', 'kaburasi'),
('Karburator', 'kaburator'),
('Karena', 'karna'),
('Karier', 'karir'),
('Karisma', 'kharisma'),
('Karismatik', 'kharismatik'),
('Kasip', 'kasep'),
('Kategori', 'katagori'),
('Katering', 'catering'),
('Kaus', 'kaos'),
('Kayangan', 'khayangan'),
('Kedaluwarsa', 'kadaluwarsa'),
('Kemarin', 'kemaren'),
('Kemboja', 'kamboja'),
('Kepok', 'gepok'),
('Kesatria', 'ksatria'),
('Khawatir', 'kuatir'),
('Klab', 'club'),
('Kles', 'clash'),
('Klien', 'clien, client'),
('Klor', 'chlor'),
('Klub', 'club'),
('Koboi', 'koboy'),
('Komoditas', 'komoditi'),
('Kompleks', 'komplek'),
('Komplet', 'komplit'),
('Konferensi', 'konperensi'),
('Kongres', 'konggres'),
('Konkret', 'kongkret'),
('Koper', 'kopor'),
('Kosakata', 'kosa kata'),
('Kover', 'cover'),
('Kreatif', 'kreatip'),
('Kreativitas', 'kreatifitas'),
('Kualitas', 'kwalitas'),
('Kuantitas', 'kwantitas'),
('Kuesioner', 'kuisioner'),
('Kuintal', 'kwintal'),
('Kuota', 'kwota'),

-- Huruf L
('Lafal', 'lapal, rapal'),
('Lamtaragung', 'lamtorogung'),
('Laskar', 'lasykar'),
('Lazim', 'lajim, lasim'),
('Leding', 'ledeng'),
('Legalisasi', 'legalisir'),
('Lemari', 'almari'),
('Lembap', 'lembab'),
('Leukemia', 'leukimia'),
('Leveransir', 'laveransir'),
('Linear', 'linier'),
('Litoral', 'literal'),
('Lobi', 'loby'),
('Lokalisasi', 'lokalisir'),
('Longmars', 'long march'),
('Lubang', 'lobang'),
('Lusin', 'losin'),

-- Huruf M
('Maaf', 'ma''af'),
('Mafhum', 'mafum'),
('Mag', 'maag'),
('Magnet', 'mahnet'),
('Magrib', 'maghrib'),
('Maizena', 'maisena'),
('Majelis', 'majilis'),
('Mak comblang', 'makcomblang'),
('Makhdum', 'makdum'),
('Makhluk', 'mahluk'),
('Makroekonomi', 'makro ekonomi'),
('Malapraktik', 'malpraktek'),
('Mampat', 'mampet'),
('Manajemen', 'managemen'),
('Manajer', 'manager'),
('Mandek', 'mandeg'),
('Mangkuk', 'mangkok'),
('Manuskrip', 'manuskrif'),
('Maraton', 'marathon'),
('Margarin', 'margarine'),
('Marginal', 'marjinal'),
('Masjid', 'mesjid'),
('Masyhur', 'mashur'),
('Matang', 'mateng'),
('Mazhab', 'madzab'),
('Memerhatikan', 'memperhatikan'),
('Memerintah', 'memperintah'),
('Memerlukan', 'memperlukan'),
('Memesona', 'mempesona'),
('Mengapa', 'kenapa'),
('Mengubah', 'merubah'),
('Menteri', 'mentri'),
('Mentimun', 'timun'),
('Menyontek', 'mencontek'),
('Menyukseskan', 'mensukseskan'),
('Merek', 'merk'),
('Meterai', 'materai'),
('Metode', 'metoda'),
('Miliar', 'milyar'),
('Modern', 'moderen'),
('Mozaik', 'mosaik'),
('Musabab', 'sebab-musabab'),
('Museum', 'musium'),

-- Huruf N
('Nafsu', 'napsu'),
('Nahas', 'naas'),
('Nakhoda', 'nahkoda, nakoda, nangkoda'),
('Nanas', 'nenas'),
('Napas', 'nafas'),
('Narasumber', 'nara sumber'),
('Nasihat', 'nasehat'),
('Nazar', 'nadzar'),
('Neokolonialisme', 'neo-kolonialisme'),
('Neto', 'netto'),
('Netralisasi', 'netralisir'),
('Nifas', 'nipas'),
('Nomor', 'nomer'),
('Nonaktif', 'non aktif'),
('Nonformal', 'non formal'),
('Notula', 'notulen'),
('November', 'nopember'),

-- Huruf O
('Objek', 'obyek'),
('Objektif', 'obyektif'),
('Ojek', 'ojeg'),
('Olahraga', 'olah raga'),
('Omzet', 'omset'),
('Orang tua', 'orangtua'),
('Oranye', 'orange'),
('Organisasi', 'organisir'),
('Orisinal', 'orisinil'),
('Orkestra', 'orchestra'),
('Osmose', 'osmosis'),
('Otomatis', 'Automatis'),

-- Huruf P
('Paderi', 'padri'),
('Paham', 'faham'),
('Palm', 'palem'),
('Pamflet', 'famplet, pamfelet'),
('Pancaindera', 'panca indra'),
('Pankreas', 'pangkreas'),
('Paradoks', 'paradox'),
('Paramedis', 'paramedik'),
('Parasut', 'parasit'),
('Parogog', 'paragoge'),
('Pascapanen', 'pasca panen'),
('Pasfoto', 'pas photo'),
('Pasif', 'pasive'),
('Paspor', 'pasport'),
('Paten', 'patent'),
('Paviliun', 'pavilyun'),
('Pedas', 'pedes'),
('Pedepokan', 'padepokan'),
('Peduli', 'perduli'),
('Pelesetan', 'plesetan'),
('Pelesir', 'plesir'),
('Peleton', 'pleton'),
('Pelihara', 'peliara, piara'),
('Pelintir', 'plintir'),
('Pembaruan', 'pembaharuan'),
('Pemirsa', 'pirsawan'),
('Penasihat', 'penasehat'),
('Penembahan', 'panembahan'),
('Perajin', 'pengrajin'),
('Peranti', 'piranti'),
('Perkedel', 'pergedel'),
('Permukiman', 'pemukiman'),
('Persentase', 'presentase, prosentase'),
('Perusak', 'pengrusak'),
('Petai', 'pete, petay'),
('Pikir', 'fikir'),
('Praktik', 'praktek'),
('Prancis', 'perancis'),
('Prangko', 'perangko'),
('Proaktif', 'pro aktif'),
('Provinsi', 'propinsi'),
('Proyek', 'project'),
('Putra', 'putera'),
('Putri', 'puteri'),

-- Huruf R
('Rabu', 'rebo'),
('Radioaktif', 'radio aktif'),
('Rakaat', 'rekaat'),
('Ramai', 'rame'),
('Ranking', 'rangking'),
('Ransel', 'rangsel'),
('Rapi', 'rapih'),
('Rapor', 'raport'),
('Rasional', 'rasionil'),
('Razia', 'rajia, rasia'),
('Real', 'riil'),
('Realisasi', 'realisir'),
('Realitas', 'realita'),
('Relief', 'relif'),
('Religius', 'relijius'),
('Rematik', 'reumatik'),
('Renaisans', 'renaisan'),
('Reptilia', 'reptil'),
('Reservoir', 'reservoar'),
('Respons', 'respon'),
('Restoran', 'restauran'),
('Resume', 'resum'),
('Rezeki', 'rejeki, rizeki, rizki'),
('Rezim', 'regim'),
('Rida', 'ridho, ridha'),
('Risiko', 'resiko'),
('Ritme', 'ritma'),
('Rontgen', 'ronsen'),
('Rubuh', 'roboh'),

-- Huruf S
('Saf', 'shaf'),
('Sah', 'syah'),
('Sahabat', 'sobat'),
('Sahaja', 'sehaja'),
('Sahdu', 'syahdu'),
('Sahib', 'sokhib'),
('Sajak', 'sanjak'),
('Sakaguru', 'saka guru guru'),
('Sakelar', 'saklar'),
('Saksama', 'seksama'),
('Salat', 'shalat, sholat'),
('Sambal', 'sambel'),
('Sampo', 'shampo'),
('Samudra', 'samudera'),
('Sangsi', 'sanksi'),
('Sanskerta', 'sansekerta'),
('Saraf', 'syaraf'),
('Satai', 'sate'),
('Saus', 'saos'),
('Sedekah', 'sodakoh'),
('Sediakala', 'sedia kala'),
('Sein', 'seign'),
('Sekadar', 'sekedar'),
('Sekop', 'skop'),
('Sekretaris', 'sekertaris'),
('Sekte', 'sekta'),
('Sekular', 'sekuler'),
('Selebritas', 'selebriti'),
('Selektivitas', 'selektifitas'),
('Selendro', 'slendro'),
('Selulosa', 'selulose'),
('Semadi', 'semedi'),
('Sembrana', 'sembrono'),
('Semenda', 'semanda'),
('Senapati', 'senopati'),
('Sengkalan', 'sangkalan'),
('Sengse', 'sinse'),
('Sentigram', 'centigram'),
('Sentimental', 'sentimentil'),
('Sentimeter', 'centimeter'),
('Sentosa', 'sentausa'),
('Sentral', 'central'),
('Sepatbor', 'sepakbor'),
('Seprai', 'seprei'),
('Sepur', 'spor'),
('Serban', 'sorban'),
('Serbaneka', 'serba aneka'),
('Seriawan', 'sariawan'),
('Serigala', 'srigala'),
('Serunai', 'seruni'),
('Servis', 'service'),
('Setagen', 'stagen'),
('Setip', 'stip'),
('Setir', 'stir'),
('Setrika', 'seterika'),
('Setrip', 'strip'),
('Seyogianya', 'seyogyanya'),
('Siapa pun', 'siapapun'),
('Siar', 'syi''ar'),
('Silakan', 'silahkan'),
('Silaturahmi', 'silaturohmi'),
('Silinder', 'selinder'),
('Simpel', 'simple'),
('Sinagoge', 'sinagog'),
('Sindrom', 'sindrome'),
('Sinkop', 'sinkope'),
('Sintesis', 'sintesa'),
('Sirene', 'sirine'),
('Sirup', 'sirop'),
('Sistem', 'sistim'),
('Ski', 'sky'),
('Skolastik', 'sekolastik'),
('Skor', 'score'),
('Skors', 'skorsing'),
('Slang', 'slank'),
('Smes', 'smash'),
('Sofbal', 'sofball'),
('Sopir', 'supir'),
('Sop', 'sup'),
('Sosiodrama', 'sosio drama'),
('Spageti', 'spagheti'),
('Spanduk', 'sepanduk'),
('Spesial', 'sepesial'),
('Spesies', 'species'),
('Spionase', 'sepionase'),
('Spiritual', 'spirituil'),
('Spons', 'sepon'),
('Sprin', 'sprint'),
('Srek', 'sreg'),
('Stan', 'stand'),
('Standar', 'standard'),
('Standardisasi', 'standarisasi'),
('Stanza', 'stansa'),
('Starter', 'stater'),
('Stereotip', 'stereotipe'),
('Stiker', 'sticker'),
('Stok', 'stock'),
('Stres', 'stress'),
('Striker', 'setriker'),
('Stroberi', 'strawberry'),
('Studi', 'study'),
('Subbab', 'sub bab'),
('Subjek', 'subyek'),
('Subkontraktor', 'sub kontraktor'),
('Subsider', 'subsidair'),
('Substansi', 'subtansi'),
('Substitusi', 'subtitusi'),
('Subtropik', 'sub tropik'),
('Subunit', 'sub unit'),
('Sukacita', 'suka cita'),
('Suling', 'seruling'),
('Sumatra', 'sumatera'),
('Suplemen', 'saplemen'),
('Supremasi', 'supermasi'),
('Surah', 'surat'),
('Surga', 'sorga'),
('Survei', 'survey'),
('Susastra', 'susastera'),
('Sutra', 'sutera'),
('Suvenir', 'souvenir'),
('Swasembada', 'swa sembada'),
('Sweter', 'suiter, switer'),
('Swipoa', 'sempoa'),
('Syafaat', 'syafa''at'),
('Syahadat', 'sahadat'),
('Syahid', 'sahid'),
('Syair', 'sair'),
('Syariat', 'syareat'),
('Syekh', 'she'),
('Syirik', 'sirik'),
('Syiwa', 'siwa'),
('Syogun', 'shogun'),
('Syubhat', 'syubat'),

-- Huruf T
('Tablig', 'tabligh'),
('Takhayul', 'tahayul'),
('Takhta', 'tahta'),
('Taksi', 'taxi'),
('Takzim', 'takjim'),
('Tampak', 'nampak'),
('Tamsil', 'tamzil'),
('Tanker', 'tangker'),
('Taoco', 'tauco'),
('Taoge', 'tauge'),
('Tapai', 'tape'),
('Taplak', 'tapelak'),
('Tarif', 'tarip'),
('Tarkhim', 'tarkim'),
('Tata niaga', 'tataniaga'),
('Tawakal', 'tawakkal'),
('Teater', 'theater'),
('Tekad', 'tekat'),
('Teknik', 'tehnik'),
('Teknologi', 'tekhnologi'),
('Teladan', 'taulada'),
('Telanjur', 'terlanjur'),
('Telantar', 'terlantar'),
('Telentang', 'terlentang'),
('Telepon', 'telpon'),
('Telur', 'telor'),
('Tenteram', 'tentram'),
('Teoretis', 'teoritis'),
('Tepercaya', 'terpercaya'),
('Terampil', 'trampil'),
('Terima kasih', 'terimakasih'),
('Tes', 'test'),
('Tesis', 'thesis'),
('Tetapi', 'tapi'),
('Tidak', 'nggak'),
('Tiket', 'ticket'),
('Tim', 'team'),
('Tip', 'tips'),
('Tipe', 'type'),
('Tobat', 'taubat'),
('Tokek', 'tekek'),
('Toleransi', 'tolerir'),
('Torpedo', 'terpedo'),
('Tradisional', 'tradisionil'),
('Transpor', 'transport'),
('Tur', 'tour'),
('Turis', 'touris'),

-- Huruf U
('Ubah', 'rubah'),
('Ukulele', 'okulele'),
('Ultramodern', 'ultra modern'),
('Unta', 'onta'),
('Urine', 'urin'),
('Utang', 'hutang'),

-- Huruf V
('Vak', 'fak'),
('Vaksinasi', 'faksinasi'),
('Vakum', 'fakum'),
('Valid', 'falid'),
('Vampir', 'vampire'),
('Vanili', 'panili'),
('Variasi', 'vareasi'),
('Varietas', 'varitas'),
('Vas', 'fas'),
('Vegetaris', 'vegetarian'),
('Verifikasi', 'veripikasi'),
('Vermak', 'vermaks'),
('Video', 'vidio'),
('Vila', 'villa'),
('Vinyet', 'vignet'),
('Volume', 'volum'),

-- Huruf W
('Wiraswasta', 'wirausaha'),

-- Huruf Y
('Yogyakarta', 'jogjakarta'),
('Yudikatif', 'judikatif'),
('Yudisial', 'judisial'),
('Yurisdiksi', 'jurisdiksi'),

-- Huruf Z
('Zaman', 'jaman'),
('Zamzam', 'zam-zam'),
('Zhuhur', 'dzuhur'),
('Zigot', 'zigote'),
('Zig-zag', 'zigzag'),
('Ziter', 'sitar'),
('Zona', 'zone');

-- Verifikasi data
SELECT COUNT(*) AS total_kata FROM kata_baku;